### ISSUE TITLE
Proper error handling

### ISSUE THREAD

**Issue by ice1000** [daskol/typst-telegram-bot#1] opened 2023-08-23 21:32 UTC
If I type a wrong command, the bot just give me the last image. Like this:

![image](https://github.com/daskol/typst-telegram-bot/assets/16398479/b824504b-a86f-420b-a9ef-5fa130430e37)

I would propose to report the error when it encounters one.

**Comment by daskol** [comment] 2023-08-24 00:10
Oh, wow! Thanks for using this bot.

> If I type a wrong command, the bot just give me the last image.

Thanks for reporting the issue. It will be fixed. (At the moment this is expected behaviour since I developed bot for private use first. Then I decided that I would improve the bot, handle errors properly and so on if there is someone who is also interested in it.)

**Comment by ice1000** [comment] 2023-08-24 03:19
Oh wow that's great! Thanks very much for hosting it!

**Comment by daskol** [comment] 2023-12-10 03:20
@ice1000 It took some time but I finally improve error handling and redeploy [@TypstBot](https://t.me/TypstBot).

**Closed as completed by daskol** 2023-12-10 03:20 UTC
Labels: bug, good first issue

**Comment by ice1000** [comment] 2023-12-10 05:36
Tyvm!

**Comment by ice1000** [comment] 2023-12-10 05:36
Tyvm!
